cp ${WORKDIR}/core/src/{*.cpp,*.h} ../../cpp/core/src
rm -f ../../cpp/core/src/softwareRelease*
cp ${WORKDIR}/core/src/{*.cpp,*.h} ../../newbler
rm -f ../../newbler/softwareRelease*
cp ${WORKDIR}/qualVal/src/{*.cc,*.cpp,*.h} ../../cpp/core/src
cp ${WORKDIR}/qualVal/src/{*.cc,*.cpp,*.h} ../../newbler
cp ${WORKDIR}/addRun/src/{*.cpp,*.h} ../../cpp/addRun/src
cp ${WORKDIR}/changeRun/src/*.cpp ../../cpp/changeRun/src
cp ${WORKDIR}/createProject/src/{*.cpp,*.h} ../../cpp/createProject/src
cp ${WORKDIR}/getProjAlignData/src/{*.cpp,*.h} ../../cpp/getProjAlignData/src
cp ${WORKDIR}/newbler/src/{*.cpp,*.h} ../../cpp/newbler/src
cp ${WORKDIR}/newbler/src/{*.cpp,*.h} ../../newbler
cp ${WORKDIR}/removeRun/src/{*.cpp,*.h} ../../cpp/removeRun/src
cp ${WORKDIR}/runAssembly/src/{*.cpp,*.h} ../../cpp/runAssembly/src
cp ${WORKDIR}/runMapping/src/{*.cpp,*.h} ../../cpp/runMapping/src
cp ${WORKDIR}/runProject/src/{*.cpp,*.h} ../../cpp/runProject/src
cp ${WORKDIR}/setRef/src/{*.cpp,*.h} ../../cpp/setRef/src
cp ${WORKDIR}/stopRun/src/{*.cpp,*.h} ../../cpp/stopRun/src
cp ${WORKDIR}/sfffile/src/{*.c,*.h} ../../sfftools/sfffile
cp ${WORKDIR}/qualVal/src/{*.cc,*.cpp,*.h} ../../sfftools/sfffile
cp ${WORKDIR}/core/src/{SffToolsProxy.*,Util.*,Types.*,InputFile.*,MIDParser.*,Logger.*,DiffUtil.*,DiffAlign.*,DiffAlignBuffer.h,SeqUtil.*,stringbuffer.*,ConfigParser.*} ../../sfftools/sfffile
#cp ~/developersEnv/AppCRelease/sfftools/sffinfo/*.c ../../sfftools/sffinfo
#cp ~/developersEnv/AppCRelease/sfftools/sff2scf/*.c ../../sfftools/sff2scf
#cp ~/developersEnv/AppCRelease/sfftools/fnafile/{*.c,*.h} ../../sfftools/fnafile
