scen1 <- read.table("s1.txt")
scen2 <- read.table("s2.txt")
scen1e <- read.table("s1e.txt")
scen2e <- read.table("s2e.txt")
chisq.test(scen1$Patients,p=scen1e$Patients)
chisq.test(data.frame(scen1$Patients,scen1$Providers))
chisq.test(data.frame(scen2$Patients,scen2$Providers))
chisq.test(data.frame(scen1$Providers,scen1$Patients))
chisq.test(data.frame(scen2$Providers,scen2$Patients))
