/* $Id: identity_nuc.pl,v 0.1alpha 2007/04/16 15:36:44 Zzz Exp $

    Part of BioProlog Logic Programming Resources for Bioinformatics

    Author:	Mauro Di Nuzzo
    E-Mail:	info@prologonlinereference.org
    WWW:	http://www.prologonlinereference.org/bioprolog.psp
    Copyright:	©2005-2007 Prolog Online Reference

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

    As a special exception, if you link this library with other files,
    compiled with a Free Software compiler, to produce an executable, this
    library does not by itself cause the resulting executable to be covered
    by the GNU General Public License. This exception does not however
    invalidate any other reasons why the executable file might be covered by
    the GNU General Public License.
*/
substitution_matrix(identity_nuc, [
	('A', 'A', 1.0),
	('A', 'B', -100),
	('A', 'C', -100),
	('A', 'D', 0.2),
	('A', 'G', -100),
	('A', 'H', 0.2),
	('A', 'K', -100),
	('A', 'M', 0.6),
	('A', 'R', 0.6),
	('A', 'S', -100),
	('A', 'T', -100),
	('A', 'U', -100),
	('A', 'V', 0.2),
	('A', 'W', 0.6),
	('A', 'Y', -100),
	('B', 'A', -100),
	('B', 'B', 0.2),
	('B', 'C', 0.2),
	('B', 'D', 0.2),
	('B', 'G', 0.2),
	('B', 'H', 0.2),
	('B', 'K', 0.2),
	('B', 'M', 0.2),
	('B', 'R', 0.2),
	('B', 'S', 0.2),
	('B', 'T', 0.2),
	('B', 'U', 0.2),
	('B', 'V', 0.2),
	('B', 'W', 0.2),
	('B', 'Y', 0.2),
	('C', 'A', -100),
	('C', 'B', 0.2),
	('C', 'C', 1.0),
	('C', 'D', -100),
	('C', 'G', -100),
	('C', 'H', 0.2),
	('C', 'K', -100),
	('C', 'M', 0.6),
	('C', 'R', -100),
	('C', 'S', 0.6),
	('C', 'T', -100),
	('C', 'U', -100),
	('C', 'V', 0.2),
	('C', 'W', -100),
	('C', 'Y', 0.6),
	('D', 'A', 0.2),
	('D', 'B', 0.2),
	('D', 'C', -100),
	('D', 'D', 0.2),
	('D', 'G', 0.2),
	('D', 'H', 0.2),
	('D', 'K', 0.2),
	('D', 'M', 0.2),
	('D', 'R', 0.2),
	('D', 'S', 0.2),
	('D', 'T', 0.2),
	('D', 'U', 0.2),
	('D', 'V', 0.2),
	('D', 'W', 0.2),
	('D', 'Y', 0.2),
	('G', 'A', -100),
	('G', 'B', 0.2),
	('G', 'C', -100),
	('G', 'D', 0.2),
	('G', 'G', 1.0),
	('G', 'H', -100),
	('G', 'K', 0.6),
	('G', 'M', -100),
	('G', 'R', 0.6),
	('G', 'S', 0.6),
	('G', 'T', -100),
	('G', 'U', -100),
	('G', 'V', 0.2),
	('G', 'W', -100),
	('G', 'Y', -100),
	('H', 'A', 0.2),
	('H', 'B', 0.2),
	('H', 'C', 0.2),
	('H', 'D', 0.2),
	('H', 'G', -100),
	('H', 'H', 0.2),
	('H', 'K', 0.2),
	('H', 'M', 0.2),
	('H', 'R', 0.2),
	('H', 'S', 0.2),
	('H', 'T', 0.2),
	('H', 'U', 0.2),
	('H', 'V', 0.2),
	('H', 'W', 0.2),
	('H', 'Y', 0.2),
	('K', 'A', -100),
	('K', 'B', 0.2),
	('K', 'C', -100),
	('K', 'D', 0.2),
	('K', 'G', 0.6),
	('K', 'H', 0.2),
	('K', 'K', 0.6),
	('K', 'M', -100),
	('K', 'R', 0.6),
	('K', 'S', 0.6),
	('K', 'T', 0.6),
	('K', 'U', 0.6),
	('K', 'V', 0.2),
	('K', 'W', 0.6),
	('K', 'Y', 0.6),
	('M', 'A', 0.6),
	('M', 'B', 0.2),
	('M', 'C', 0.6),
	('M', 'D', 0.2),
	('M', 'G', -100),
	('M', 'H', 0.2),
	('M', 'K', -100),
	('M', 'M', 0.6),
	('M', 'R', 0.6),
	('M', 'S', 0.6),
	('M', 'T', -100),
	('M', 'U', -100),
	('M', 'V', 0.2),
	('M', 'W', 0.6),
	('M', 'Y', 0.6),
	('R', 'A', 0.6),
	('R', 'B', 0.2),
	('R', 'C', -100),
	('R', 'D', 0.2),
	('R', 'G', 0.6),
	('R', 'H', 0.2),
	('R', 'K', 0.6),
	('R', 'M', 0.6),
	('R', 'R', 0.6),
	('R', 'S', 0.6),
	('R', 'T', -100),
	('R', 'U', -100),
	('R', 'V', 0.2),
	('R', 'W', 0.6),
	('R', 'Y', -100),
	('S', 'A', -100),
	('S', 'B', 0.2),
	('S', 'C', 0.6),
	('S', 'D', 0.2),
	('S', 'G', 0.6),
	('S', 'H', 0.2),
	('S', 'K', 0.6),
	('S', 'M', 0.6),
	('S', 'R', 0.6),
	('S', 'S', 0.6),
	('S', 'T', -100),
	('S', 'U', -100),
	('S', 'V', 0.2),
	('S', 'W', -100),
	('S', 'Y', 0.6),
	('T', 'A', -100),
	('T', 'B', 0.2),
	('T', 'C', -100),
	('T', 'D', 0.2),
	('T', 'G', -100),
	('T', 'H', 0.2),
	('T', 'K', 0.6),
	('T', 'M', -100),
	('T', 'R', -100),
	('T', 'S', -100),
	('T', 'T', 1.0),
	('T', 'U', 1.0),
	('T', 'V', -100),
	('T', 'W', 0.6),
	('T', 'Y', 0.6),
	('U', 'A', -100),
	('U', 'B', 0.2),
	('U', 'C', -100),
	('U', 'D', 0.2),
	('U', 'G', -100),
	('U', 'H', 0.2),
	('U', 'K', 0.6),
	('U', 'M', -100),
	('U', 'R', -100),
	('U', 'S', -100),
	('U', 'T', 1.0),
	('U', 'U', 1.0),
	('U', 'V', -100),
	('U', 'W', 0.6),
	('U', 'Y', 0.6),
	('V', 'A', 0.2),
	('V', 'B', 0.2),
	('V', 'C', 0.2),
	('V', 'D', 0.2),
	('V', 'G', 0.2),
	('V', 'H', 0.2),
	('V', 'K', 0.2),
	('V', 'M', 0.2),
	('V', 'R', 0.2),
	('V', 'S', 0.2),
	('V', 'T', -100),
	('V', 'U', -100),
	('V', 'V', 0.2),
	('V', 'W', 0.2),
	('V', 'Y', 0.2),
	('W', 'A', 0.6),
	('W', 'B', 0.2),
	('W', 'C', -100),
	('W', 'D', 0.2),
	('W', 'G', -100),
	('W', 'H', 0.2),
	('W', 'K', 0.6),
	('W', 'M', 0.6),
	('W', 'R', 0.6),
	('W', 'S', -100),
	('W', 'T', 0.6),
	('W', 'U', 0.6),
	('W', 'V', 0.2),
	('W', 'W', 0.6),
	('W', 'Y', 0.6),
	('Y', 'A', -100),
	('Y', 'B', 0.2),
	('Y', 'C', 0.6),
	('Y', 'D', 0.2),
	('Y', 'G', -100),
	('Y', 'H', 0.2),
	('Y', 'K', 0.6),
	('Y', 'M', 0.6),
	('Y', 'R', -100),
	('Y', 'S', 0.6),
	('Y', 'T', 0.6),
	('Y', 'U', 0.6),
	('Y', 'V', 0.2),
	('Y', 'W', 0.6),
	('Y', 'Y', 0.6)
]).
