NEWBLER = read.table('NEWBLER.length')
MIRA = read.table('MIRA.length')
PHRAP = read.table('PHRAP.length')
CAP3 = read.table('CAP3.length')
par(mfrow = c(2,2))
hist(MIRA$V1, xlab = "Contig Length", col="blue", border="black", main = "MIRA", breaks=1000,xlim=c(0,10000))
hist(PHRAP$V1, xlab = "Contig Length", col="red", border="black", main = "PHRAP", breaks=1000,xlim=c(0,10000))
hist(CAP3$V1, xlab = "Contig Length", col="green", border="black", main = "CAP3", breaks=1000,xlim=c(0,10000))
hist(NEWBLER$V1, xlab = "Contig Length", col="black", border="black", main = "NEWBLER", breaks=1000,xlim=c(0,10000))

